server:
  port: 8090

spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.0.76:3306/tk_mysql?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
                           # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
      view:
        suffix: .jsp
        prefix: /WEB-INF/jsp/
      thymeleaf:
        cache: false
        enabled: false
    resources:
      static-locations: classpath:/WEB-INF/resources
    http:
      multipart:
        max-file-size: 100Mb
        max-request-size: 100Mb
